name: Test What time is it
on:
  [push]

jobs:
  what_time_is_it_job:
    runs-on: ubuntu-latest
    name: What time is it?

    steps:
    - name: Checkout step
      uses: actions/checkout@v2
    - name: What time is it step
      uses: ./
      id: get-time
      with: 
        time-zone: 'Europe/Madrid'
    - name: Output
      run: echo "Your time is ${{ steps.get-time.outputs.time}}"
